@apiUrl = http://localhost:3000
@id = 308
@query = żłobek

### Hello world endpoint
GET {{apiUrl}}

### Get all institutions
GET {{apiUrl}}/institutions

### Get by id
GET {{apiUrl}}/institutions/details/{{id}}

### Get by search query
GET {{apiUrl}}/institutions/autocomplete?search={{query}}

### Get all locations
GET {{apiUrl}}/locations

### Get all cities
GET {{apiUrl}}/cities